[[mqtt]]
= MQTT Support

[[mqtt-intro]]
== Introduction

Spring Integration provides inbound and outbound channel adapters supporting the MQ Telemetry Transport (MQTT) protocol. The current implementation uses the http://www.eclipse.org/paho/[Eclipse Paho MQTT Client] library.

Configuration of both adapters is achieved using the `DefaultMqttPahoClientFactory`. Refer to the Paho documentation for more information about configuration options.

[[mqtt-inbound]]
== Inbound (message-driven) Channel Adapter

The inbound channel adapter is implemented by the `MqttPahoMessageDrivenChannelAdapter`. For convenience, it can be configured using the namespace. A minimal configuration might be:

[source,xml]
----
<bean id="clientFactory"
		class="org.springframework.integration.mqtt.core.DefaultMqttPahoClientFactory">
	<property name="userName" value="${mqtt.username}"/>
	<property name="password" value="${mqtt.password}"/>
</bean>

<int-mqtt:message-driven-channel-adapter id="mqttInbound"
	client-id="${mqtt.default.client.id}.src"
	url="${mqtt.url}"
	topics="sometopic"
	client-factory="clientFactory"
	channel="output"/>
----

Attributes:

[source]
----
<int-mqtt:message-driven-channel-adapter id="oneTopicAdapter"
	client-id="foo" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-i-01]
	url="tcp://localhost:1883" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-i-02]
	topics="bar,baz" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-i-03]
	qos="1,2" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-i-03a]
	converter="myConverter" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-i-04]
	client-factory="clientFactory" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-i-05]
	send-timeout="123" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-i-06]
	error-channel="errors" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-i-07]
	channel="out" />
----

TBD Section qName:calloutlist level:3, chunks:[
			, TBD Section qName:callout level:4, chunks:[
				The client id.
			] attrs:[arearefs:mqtt-i-01], 
			, TBD Section qName:callout level:4, chunks:[
				, Paragraph: chunks:[
					The broker URL.
				], 
				, Note Section qName:note level:5, chunks:[
					Starting with , Bold Section qName:emphasis level:6, chunks:[version 4.1] attrs:[:],  the url can be omitted and, instead,
					the server URIs can be provided in the , Monospaced ([serverURIs]),  property of the
					, Monospaced ([DefaultMqttPahoClientFactory]), . This enables, for example,
					connection to a highly available (HA) cluster., 
				] attrs:[:], 
			] attrs:[arearefs:mqtt-i-02], 
			, TBD Section qName:callout level:4, chunks:[
				A comma delimited list of topics from which this adapter will receive messages.
			] attrs:[arearefs:mqtt-i-03], 
			, TBD Section qName:callout level:4, chunks:[
				A comma delimited list of QoS values. Can be a single value that is applied to all
				topics, or a value for each topic (in which case the lists must the same length)., 
			] attrs:[arearefs:mqtt-i-03a], 
			, TBD Section qName:callout level:4, chunks:[
				An , Monospaced ([MqttMessageConverter]),  (optional). The default
				, Monospaced ([DefaultPahoMessageConverter]),  produces a message with a , Monospaced ([String]), 
				payload (by default) with the following headers:
				, ItemizedList Section qName:itemizedlist level:5, chunks:[
					, ListItem Section qName:listitem level:6, chunks:[Monospaced ([mqtt_topic]),  - the topic from which the message was received] attrs:[:], 
					, ListItem Section qName:listitem level:6, chunks:[Monospaced ([mqtt_duplicate]),  - true if the message is a duplicate] attrs:[:], 
					, ListItem Section qName:listitem level:6, chunks:[Monospaced ([mqtt_qos]),  - the quality of service] attrs:[:], 
				] attrs:[:], 
				The , Monospaced ([DefaultPahoMessageConverter]),  can be configured to return the raw
				, Monospaced ([byte[]]),  in the payload by declaring it as a , <, bean/, >,  and setting the
				, Monospaced ([payloadAsBytes]),  property.
			] attrs:[arearefs:mqtt-i-04], 
			, TBD Section qName:callout level:4, chunks:[
				The client factory.
			] attrs:[arearefs:mqtt-i-05], 
			, TBD Section qName:callout level:4, chunks:[
				The send timeout - only applies if the channel might block (such as a bounded , Monospaced ([QueueChannel]), 
				that is currently full).
			] attrs:[arearefs:mqtt-i-06], 
			, TBD Section qName:callout level:4, chunks:[
				The error channel - downstream exceptions will be sent to this channel, if supplied, in an
				, Monospaced ([ErrorMessage]), ; the payload is a , Monospaced ([MessagingException]), 
				containing the failed message and cause.
			] attrs:[arearefs:mqtt-i-07], 
		] attrs:[:]=== Adding/Removing Topics at Runtime

Starting with *version 4.1*, it is possible to programmatically change the topics to which the adapter is subscribed. Methods `addTopic()` and `removeTopic()` are provided. When adding topics, you can optionally specify the `QoS` (default: 1). You can also modify the topics by sending an appropriate message to a `<control-bus/>` with an appropriate payload: `"myMqttAdapter.addTopic('foo', 1)"`.

Stopping/starting the adapter has no effect on the topic list (it does *not* revert to the original settings in the configuration). The changes are not retained beyond the life cycle of the application context; a new application context will revert to the configured settings.

Changing the topics while the adapter is stopped (or disconnected from the broker) will take effect the next time a connection is established.

[[mqtt-outbound]]
== Outbound Channel Adapter

The outbound channel adapter is implemented by the `MqttPahoMessageHandler` which is wrapped in a `ConsumerEndpoint`. For convenience, it can be configured using the namespace.

Starting with *version 4.1*, the adapter supports asynchronous sends, avoiding blocking until the delivery is confirmed; application events can be emitted to enable applications to confirm delivery if desired.

Attributes:

[source]
----
<int-mqtt:outbound-channel-adapter id="withConverter"
	client-id="foo" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-o-01]
	url="tcp://localhost:1883" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-o-02]
	converter="myConverter" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-o-03]
	client-factory="clientFactory" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-o-04]
	default-qos="1" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-o-05]
	default-retained="true" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-o-06]
	default-topic="bar" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-o-07]
	async="false" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-o-08]
	async-events="false" TBD Section qName:co level:4, chunks:[] attrs:[id:mqtt-o-09]
	channel="target" />
----

TBD Section qName:calloutlist level:3, chunks:[
			, TBD Section qName:callout level:4, chunks:[
				The client id.
			] attrs:[arearefs:mqtt-o-01], 
			, TBD Section qName:callout level:4, chunks:[
				, Paragraph: chunks:[
					The broker URL.
				], 
				, Note Section qName:note level:5, chunks:[
					Starting with , Bold Section qName:emphasis level:6, chunks:[version 4.1] attrs:[:],  the url can be omitted and, instead,
					the server URIs can be provided in the , Monospaced ([serverURIs]),  property of the
					, Monospaced ([DefaultMqttPahoClientFactory]), . This enables, for example,
					connection to a highly available (HA) cluster., 
				] attrs:[:], 
			] attrs:[arearefs:mqtt-o-02], 
			, TBD Section qName:callout level:4, chunks:[
				An , Monospaced ([MqttMessageConverter]),  (optional). The default
				, Monospaced ([DefaultPahoMessageConverter]), 
				recognizes the following headers:
				, ItemizedList Section qName:itemizedlist level:5, chunks:[
					, ListItem Section qName:listitem level:6, chunks:[Monospaced ([mqtt_topic]),  - the topic to which the message will be sent] attrs:[:], 
					, ListItem Section qName:listitem level:6, chunks:[Monospaced ([mqtt_retained]),  - true if the message is to be retained] attrs:[:], 
					, ListItem Section qName:listitem level:6, chunks:[Monospaced ([mqtt_qos]),  - the quality of service] attrs:[:], 
				] attrs:[:], 
			] attrs:[arearefs:mqtt-o-03], 
			, TBD Section qName:callout level:4, chunks:[
				The client factory.
			] attrs:[arearefs:mqtt-o-04], 
			, TBD Section qName:callout level:4, chunks:[
				The default quality of service (used if no , Monospaced ([mqtt_qos]),  header is found). Not allowed
				if a custom , Monospaced ([converter]),  is supplied.
			] attrs:[arearefs:mqtt-o-05], 
			, TBD Section qName:callout level:4, chunks:[
				The default value of the retained flag (used if no , Monospaced ([mqtt_retaind]),  header is found). Not allowed
				if a custom,  , Monospaced ([converter]),  is supplied.
			] attrs:[arearefs:mqtt-o-06], 
			, TBD Section qName:callout level:4, chunks:[
				The default topic to which the message will be sent (used if no , Monospaced ([mqtt_topic]),  header is found).
			] attrs:[arearefs:mqtt-o-07], 
			, TBD Section qName:callout level:4, chunks:[
				When , Monospaced ([true]), , the caller will not block waiting for delivery confirmation when a message is
				sent., 
				Default:false (the send blocks until delivery is confirmed).
			] attrs:[arearefs:mqtt-o-08], 
			, TBD Section qName:callout level:4, chunks:[
				When , Monospaced ([async]),  and , Monospaced ([async-events]),  are both , Monospaced ([true]), , an
				, Monospaced ([MqttMessageSentEvent]),  is emitted, containing the message, the
				topic, the , Monospaced ([messageId]),  generated by the client library, the , Monospaced ([clientId]), 
				and the , Monospaced ([clientInstance]),  (incremented each time the client is connected).
				When the delivery is confirmed by the client library, an, 
				, Monospaced ([MqttMessageDeliveredEvent]),  is emitted, containing the the , Monospaced ([messageId]), ,
				, Monospaced ([clientId]),  and the , Monospaced ([clientInstance]), , enabling
				delivery to be correlated with the send. These events can be received by any, 
				, Monospaced ([ApplicationListener]), , or by an event inbound channel adapter. Note that
				it is possible that the , Monospaced ([MqttMessageDeliveredEvent]),  might be received before
				the , Monospaced ([MqttMessageSentEvent]), .
				Default: , Monospaced ([false]), .
			] attrs:[arearefs:mqtt-o-09], 
		] attrs:[:]
