[[resequencer]]
= Resequencer

== Introduction

Related to the Aggregator, albeit different from a functional standpoint, is the Resequencer.

[[resequencer-functionality]]
== Functionality

The Resequencer works in a similar way to the Aggregator, in the sense that it uses the CORRELATION_ID to store messages in groups, the difference being that the Resequencer does not process the messages in any way. It simply releases them in the order of their SEQUENCE_NUMBER header values.

With respect to that, the user might opt to release all messages at once (after the whole sequence, according to the SEQUENCE_SIZE, has been released), or as soon as a valid sequence is available.

== Configuring a Resequencer

Configuring a resequencer requires only including the appropriate element in XML.

A sample resequencer configuration is shown below.

[source,xml]
----
<int:channel id="inputChannel"/>

<int:channel id="outputChannel"/>

<int:resequencer id="completelyDefinedResequencer" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml1-co, linkends:resxml1]
  input-channel="inputChannel" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml2-co, linkends:resxml2]
  output-channel="outputChannel" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml3-co, linkends:resxml3]
  discard-channel="discardChannel" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml4-co, linkends:resxml4]
  release-partial-sequences="true" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml5-co, linkends:resxml5]
  message-store="messageStore" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml6-co, linkends:resxml6]
  send-partial-result-on-expiry="true" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml7-co, linkends:resxml7]
  send-timeout="86420000" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml10-co, linkends:resxml10]
  correlation-strategy="correlationStrategyBean" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml11-co, linkends:resxml11]
  correlation-strategy-method="correlate" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml12-co, linkends:resxml12]
  correlation-strategy-expression="headers['foo']" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml13-co, linkends:resxml13]
  release-strategy="releaseStrategyBean" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml14-co, linkends:resxml14]
  release-strategy-method="release" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml15-co, linkends:resxml15]
  release-strategy-expression="size() == 10" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml16-co, linkends:resxml16]
  empty-group-min-timeout="60000" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml17-co, linkends:resxml17]

  lock-registry="lockRegistry" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml18]

  group-timeout="60000" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml19]
  group-timeout-expression="size() ge 2 ? 100 : -1" TBD Section qName:co level:4, chunks:[] attrs:[id:resxml20]
  scheduler="taskScheduler" /> TBD Section qName:co level:4, chunks:[] attrs:[id:resxml21]
----

TBD Section qName:calloutlist level:4, chunks:[
        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[The id of the resequencer is
          , Bold Section qName:emphasis level:7, chunks:[optional] attrs:[:], .], 
        ] attrs:[arearefs:resxml1-co, id:resxml1], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[The input channel of the resequencer.
          , Bold Section qName:emphasis level:7, chunks:[Required] attrs:[:], .], 
        ] attrs:[arearefs:resxml2-co, id:resxml2], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[The channel to which the resequencer will send the reordered
          messages. , Bold Section qName:emphasis level:7, chunks:[Optional] attrs:[:], .], 
        ] attrs:[arearefs:resxml3-co, id:resxml3], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[The channel to which the resequencer will send the messages that
          timed out (if , Monospaced ([send-partial-result-on-timeout]),  is
          , Bold Section qName:emphasis level:7, chunks:[false)] attrs:[:], . , Bold Section qName:emphasis level:7, chunks:[Optional] attrs:[:], .], 
        ] attrs:[arearefs:resxml4-co, id:resxml4], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[Whether to send out ordered sequences as soon as they are
          available, or only after the whole message group arrives., 
          , Bold Section qName:emphasis level:7, chunks:[Optional (false by default)] attrs:[:], .], 
        ] attrs:[arearefs:resxml5-co, id:resxml5], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[A reference to a , Monospaced ([MessageGroupStore]),  that can be
          used to store groups of messages under their correlation key until, 
          they are complete. , Bold Section qName:emphasis level:7, chunks:[Optional] attrs:[:],  with default a
          volatile in-memory store.], 
        ] attrs:[arearefs:resxml6-co, id:resxml6], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[Whether, upon the expiration of the group, the ordered group
          should be sent out (even if some of the messages are missing)., 
          , Bold Section qName:emphasis level:7, chunks:[Optional (false by default)] attrs:[:], . See , Xref (Section qName:xref level:7, chunks:[] attrs:[linkend:reaper]), .], 
        ] attrs:[arearefs:resxml7-co, id:resxml7], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[The timeout for sending out messages.
          , Bold Section qName:emphasis level:7, chunks:[Optional] attrs:[:], .], 
        ] attrs:[arearefs:resxml10-co, id:resxml10], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[A reference to a bean that implements the message correlation (grouping)
          algorithm. The bean can be an implementation of the , Monospaced ([CorrelationStrategy]), 
          interface or a POJO. In the latter case the correlation-strategy-method attribute must be defined
          as well. , Bold Section qName:emphasis level:7, chunks:[Optional (by default, the aggregator will use
          the , Monospaced ([IntegrationMessageHeaderAccessor.CORRELATION_ID]),  header) ] attrs:[:], .], 
        ] attrs:[arearefs:resxml11-co, id:resxml11], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[A method defined on the bean referenced by
          , Monospaced ([correlation-strategy]), , that implements the
          correlation decision algorithm. , Bold Section qName:emphasis level:7, chunks:[Optional, with
          restrictions (requires , Monospaced ([correlation-strategy]),  to be
          present).] attrs:[:]], 
        ] attrs:[arearefs:resxml12-co, id:resxml12], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[A SpEL expression representing the correlation strategy.
          Example: , Monospaced (["headers['foo']"]), . Only one of , Monospaced ([correlation-strategy]), 
          or , Monospaced ([correlation-strategy-expression]),  is allowed.], 
        ] attrs:[arearefs:resxml13-co, id:resxml13], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[A reference to a bean that implements the release strategy.
          The bean can be an implementation of the , Monospaced ([ReleaseStrategy]),  interface
          or a POJO. In the latter case the release-strategy-method, 
          attribute must be defined as well. , Bold Section qName:emphasis level:7, chunks:[Optional (by default, the
          aggregator will use the , Monospaced ([IntegrationMessageHeaderAccessor.SEQUENCE_SIZE]),  header attribute)] attrs:[:], .], 
        ] attrs:[arearefs:resxml14-co, id:resxml14], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[A method defined on the bean referenced by
          , Monospaced ([release-strategy]), , that implements the
          completion decision algorithm. , Bold Section qName:emphasis level:7, chunks:[Optional, with
          restrictions (requires , Monospaced ([release-strategy]),  to be
          present).] attrs:[:]], 
        ] attrs:[arearefs:resxml15-co, id:resxml15], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[A SpEL expression representing the release strategy; the root object for the
          expression is a , Monospaced ([Collection]),  of , Monospaced ([Message]), s.
          Example: , Monospaced (["size() == 5"]), . Only one of
          , Monospaced ([release-strategy]), 
          or , Monospaced ([release-strategy-expression]),  is allowed.], 
        ] attrs:[arearefs:resxml16-co, id:resxml16], 

        , TBD Section qName:callout level:5, chunks:[
          , Paragraph: chunks:[Only applies if a , Monospaced ([MessageGroupStoreReaper]),  is configured
          for the , Monospaced ([<, resequcencer, >]), 's , Monospaced ([MessageStore]), .
          By default, when a , Monospaced ([MessageGroupStoreReaper]),  is configured to expire partial
          groups, empty groups are also removed. Empty groups exist after a group, 
          is released normally. This is to enable the detection and discarding of
          late-arriving messa, ges. If you wish to expire empty groups on a longer
          schedule than expiring partial groups, set this property. Empty groups will, 
          then not be removed from the , Monospaced ([MessageStore]),  until they have not been modified
          for at least this number of milliseconds. Note that the actual time to expire an, 
          empty group will also be affected by the reaper's , Bold Section qName:emphasis level:7, chunks:[timeout] attrs:[:], 
          property and it could be as much as this value plus the timeout.], 
        ] attrs:[arearefs:resxml17-co, id:resxml17], 
		, TBD Section qName:callout level:5, chunks:[
			, Paragraph: chunks:[
				See , Xref (Section qName:xref level:7, chunks:[] attrs:[linkend:aggregator-xml]), .
			], 
		] attrs:[arearefs:resxml18], 

		, TBD Section qName:callout level:5, chunks:[
			, Paragraph: chunks:[
				See , Xref (Section qName:xref level:7, chunks:[] attrs:[linkend:aggregator-xml]), .
			], 
		] attrs:[arearefs:resxml19], 
		, TBD Section qName:callout level:5, chunks:[
			, Paragraph: chunks:[
				See , Xref (Section qName:xref level:7, chunks:[] attrs:[linkend:aggregator-xml]), .
			], 
		] attrs:[arearefs:resxml20], 
		, TBD Section qName:callout level:5, chunks:[
			, Paragraph: chunks:[
				See , Xref (Section qName:xref level:7, chunks:[] attrs:[linkend:aggregator-xml]), .
			], 
		] attrs:[arearefs:resxml21], 
      ] attrs:[:]

NOTE: Since there is no custom behavior to be implemented in Java classes for resequencers, there is no annotation support for it.

